#summary Rethrowing exceptions
#labels Keyword

= `rethrow` keyword =

== Rethrowing exceptions ==

`rethrow` throws again the currently thrown exception, with a new message.

This macro creates a new instance of the thrown exception, with a more specific message. 

`rethrow` is intended to be used in a `catch` block and the purpose is to refine the message of the currently caught exception. The previous exception (and its message) will be stored as the _cause_ of the newly thrown exception. 

{{{
try{
    image = read_file(file_path);
}catch(FileOpenException){
    rethrow("Image not found.");
}
}}}

The semantics of this macro are the same as for the throw macro. 

== See also ==

 * *[throw]*
 * *[rethrowf]*


----

[http://exceptions4c.googlecode.com/svn/trunk/etc/exceptions4c_128.png]